# Generated by Django 5.2.4 on 2025-08-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_length',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(),
        ),
    ]
