# Generated by Django 5.2.4 on 2025-08-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_album_album_length_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsong',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='playlists.playlist'),
        ),
    ]
