# Generated by Django 5.2.4 on 2025-08-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlistsong_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
    ]
